### ISSUE TITLE
Compilation error on node 5.3.0

### ISSUE THREAD

**Issue by NoxHarmonium** [thegregorator/ttembed-js#3]
Hi,

ttembed-js doesn't seem to compile for me. It might be because I am using a recent version of node.

NPM version 3.3.12
Node version 5.3.0

```
../fs-ext.cc:91:23: error: unknown type name 'uv_work_t'
static void EIO_After(uv_work_t *req) {
                      ^
../fs-ext.cc:92:15: error: calling a protected constructor of class
      'v8::HandleScope'
  HandleScope scope;
              ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:889:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../fs-ext.cc:106:15: warning: 'ErrnoException' is deprecated: Use
      ErrnoException(isolate, ...) [-Wdeprecated-declarations]
    argv[0] = ErrnoException(store_data->error);
              ^
/Users/seandawson/.node-gyp/5.3.0/include/node/node.h:100:45: note:
      'ErrnoException' has been explicitly marked deprecated here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/seandawson/.node-gyp/5.3.0/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:109:33: error: no matching function for call to 'Null'
    argv[0] = Local<Value>::New(Null());
                                ^~~~
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:8120:18: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
Local<Primitive> Null(Isolate* isolate) {
                 ^
../fs-ext.cc:120:49: error: too few arguments to function call, expected 2, have
      1
        argv[1] = Number::New(store_data->offset);
                  ~~~~~~~~~~~                   ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:125:38: error: too few arguments to function call, single argument
      'isolate' was not specified
        statvfs_result = Object::New();
                         ~~~~~~~~~~~ ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2930:3: note: 'New' declared
      here
  static Local<Object> New(Isolate* isolate);
  ^
../fs-ext.cc:127:93: error: too few arguments to function call, expected 2, have
      1
  ...Integer::New(store_data->statvfs_buf.f_namemax));
     ~~~~~~~~~~~~                                  ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2496:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../fs-ext.cc:128:89: error: too few arguments to function call, expected 2, have
      1
  ...Integer::New(store_data->statvfs_buf.f_bsize));
     ~~~~~~~~~~~~                                ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2496:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../fs-ext.cc:129:91: error: too few arguments to function call, expected 2, have
      1
  ...Integer::New(store_data->statvfs_buf.f_frsize));
     ~~~~~~~~~~~~                                 ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2496:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../fs-ext.cc:130:90: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_blocks));
     ~~~~~~~~~~~                                 ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:131:90: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_bavail));
     ~~~~~~~~~~~                                 ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:132:88: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_bfree));
     ~~~~~~~~~~~                                ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:133:88: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_files));
     ~~~~~~~~~~~                                ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:134:90: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_favail));
     ~~~~~~~~~~~                                 ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:135:88: error: too few arguments to function call, expected 2, have
      1
  ...Number::New(store_data->statvfs_buf.f_ffree));
     ~~~~~~~~~~~                                ^
/Users/seandawson/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../fs-ext.cc:147:22: error: member reference type 'Persistent<v8::Function>' is
      not a pointer; maybe you meant to use '.'?
  (*(store_data->cb))->Call(v8::Context::GetCurrent()->Global(), argc, argv);
  ~~~~~~~~~~~~~~~~~~~^~
                     .
../fs-ext.cc:147:24: error: no member named 'Call' in
      'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
  (*(store_data->cb))->Call(v8::Context::GetCurrent()->Global(), argc, argv);
  ~~~~~~~~~~~~~~~~~~~  ^
../fs-ext.cc:147:42: error: no member named 'GetCurrent' in 'v8::Context'
  (*(store_data->cb))->Call(v8::Context::GetCurrent()->Global(), argc, argv);
                            ~~~~~~~~~~~~~^
../fs-ext.cc:150:5: warning: 'FatalException' is deprecated: Use
      FatalException(isolate, ...) [-Wdeprecated-declarations]
    FatalException(try_catch);
    ^
/Users/seandawson/.node-gyp/5.3.0/include/node/node.h:283:29: note:
      'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/Users/seandawson/.node-gyp/5.3.0/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../fs-ext.cc:154:3: error: use of undeclared identifier 'cb_destroy'
  cb_destroy(store_data->cb);
  ^
../fs-ext.cc:159:25: error: unknown type name 'uv_work_t'
static void EIO_StatVFS(uv_work_t *req) {
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/ttembed-js/node_modules/fs-ext
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:fs-ext@0.3.2 fs-ext@0.3.2 install: `node-gyp configure build`
npm WARN install:fs-ext@0.3.2 Exit status 1
```

**Comment by sheff146** [comment]
I have the same issue on node 4.4. I created a PR https://github.com/thegregorator/ttembed-js/pull/4 to fix this.

**Comment by MelchnerRoman** [comment]
@sheff146 your pr works - thank you 👍
